spring.application.name=j2

spring.mongodb.uri=mongodb+srv://kavishvachheta2_db_user:EFL7X5Ll08nQf2Fi@cluster0.746di7e.mongodb.net/JournalentriesDb?retryWrites=true&w=majority&appName=Cluster0

weather.api.key=3130d2ce119e343162f2febbed2e458b

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kavishvachheta11@gmail.com
spring.mail.password=mtcncboeyqkcevsq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.data.redis.host=localhost
spring.data.redis.url=redis://default:AAhIg1ZItASY1kYLyiJBzM3Y0UxbWdBa@thought-central-orange-21127.db.redis.io:14586
